language: csharp
solution: Twilio.sln
mono: latest
dotnet: 3.1
services:
- docker
jobs:
  include:
    - language: csharp
      dotnet: '3.1'
      after_success:
        - sonar-scanner
script:
- make test
- make release
deploy:
- provider: script
  script: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    && make docker-build && make docker-push
  skip_cleanup: true
  on:
    branch: main
    tags: true
- provider: script
  script: dotnet nuget push **/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  skip_cleanup: true
  on:
    branch: main
    tags: true
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: MoZ9nM/oIwiLOa8In+Dp9KpGVlHBTW5zGwJ8v5TgmOAdWPph0cP+8C4q/qR0s3UPejQflWA0u7g92Yr6X9eaPiGR5o/JGzTGW8hgW0bCylHLdxwEGSrbg3bPOFV2kyGYHVbiJHUNSwY/wQY6sdglD3xetviCN3u3bJQYixzPv3o=
addons:
  sonarcloud:
    organization: "twilio"
    token:
      secure: iY4zCMK1pW4IOut1kXjqUSusES8LsBJgv0yirf7IyvQQvH6jGp70q0u053ZuZaZdiN8lLuzoOWUX8k1wcQSD1PXRtI77uhpHy7TYHecQy9kK4WTKgzN/zVVkO2MNPgT+bSmLMWJL6WJ3HT2TZ9Nu4j+6jvy1sNB5CWZ7vySvcas=
